### ISSUE TITLE
Double check master list and rerun make file

### ISSUE THREAD

**Issue by hputnam** [hputnam/Moorea_Sym#1]
I have uploaded the original Yost_1944Fasta09132012.zip to the google drive as well as the original sample submission form (YOST-GATES SubmissionForm_July 2012_Original AmSam_Moorea submission.xls). The zip will have a txt files with the sample names. The prior extra M issue had to do with Denise naming barcode numbers the same so I had added an M to clarify things in my mind.  For the correct data we should go with the match between the sample submission form names and txt file names and the names in the fna file.  The other issue of number 127 is also clarified by the original sample submission form.  Use 127. Do not use "137 is 127".

**Comment by jrcunning** [comment]
I'm still a bit unclear on which samples to use. The sample names in the 'YOST-GATES SubmissionForm' do not contain any M's after the numbers, but the sample names in the SampleID column of Yost_1944F.txt do have M's, so they do not all correspond....

**Comment by jrcunning** [comment]
OK I went through the sample IDs in the txt file included in the Yost_1944Fasta09132012.zip archive and selected only the SampleIDs that were for Moorea samples (n=58), some of which had M's after (if AS sample with same number also existed), and some of which did not (if sample number was unique to a Moorea sample). I have a script locally that filters out all of the non-Moorea samples, then removes the M's from the end of the Moorea sample numbers that have them, and creates a new "Moorea_seqs.tar.gz" archive, which was then copied into the Bioinf directory. Let me know if you want to see this script or add it to the repo to make sure you agree that correct samples are now included...

Reran the Makefile with the new sequence file...

**Comment by hputnam** [comment]
maybe we can dump the old versions in GH and retain this one for clear tracking for downstream analysis?? It would be good to have one "notebook" of a md file or jupyter notebook that has all steps that we can submit as a supplemental file.

If you want to dump the script in too, I can take a look at it.  I agree with your filtering and can check the repo before Wed.  Thanks!

**Comment by daniclaar** [comment]
Seems like it would make sense to dump the old versions in GH, to keep things clear.
I also like the idea of either a md file or jupyter notebook, although isn't that sort of what the Makefile is doing? Maybe we can comment the Makefile, or have a corresponding README?
