### ISSUE TITLE
Set initial and biweekly meetings

### ISSUE THREAD

**Issue by hputnam** [hputnam/Moorea_Sym#2]
What works for you guys next week?

**Comment by daniclaar** [comment]
My schedule is pretty flexible next week! Let me know what works for you guys.

**Comment by jrcunning** [comment]
sounds like we are all pretty open... how about Wednesday at 2pm EST?

**Comment by daniclaar** [comment]
Sounds good to me!

**Comment by hputnam** [comment]
Perfect... set for skype on Wed. March 1 at 2pm eastern!
