### ISSUE TITLE
Calculate MMM from Moorea LTER temperature

### ISSUE THREAD

**Issue by daniclaar** [hputnam/Moorea_Sym#20]
And compare to satellite MMM, and our current (placeholder) thresholds of 30 and 31.

**Comment by daniclaar** [comment]
Using both MCR.1 and MCR.6, the in situ maximum monthly mean is 28.80376, and the bleaching hotspot (MMM+1) is 29.90376. - this is very similar to our current threshold of 30 degrees.

Note that the MMM for each site individually both occurred in April, and were MCR.1=28.84236 and MCR.6=28.76515

**Comment by daniclaar** [comment]
Using the satellite product, the MMM near sites 1, 2, and 3 is 28.7351, and near sites 7, 8, 9 is 28.7244, the mean of these two is 28.72975. The bleaching hotspot, then is 29.73. Both satellite MMMs occurred in March.

Note that the in situ hotspot (29.9 deg C) is nearly the same as the satellite hotspot (29.7 deg C). I'd potentially trust the satellite one more, as it is based on a 1982-2014 climatology (compared to the shorter in situ climatology I calculated based on the Moorea LTER).
We can change the threshold (daysabove30) to either 29.9 or 29.7, although I doubt that it will make much difference to the end result (e.g. PCAs, etc).

**Comment by hputnam** [comment]
Thanks @daniclaar !!
