### ISSUE TITLE
Re run PCA, PC tests, and NMDS with phylogenetically-informed beta diversity

### ISSUE THREAD

**Issue by daniclaar** [hputnam/Moorea_Sym#22]
(once tree/beta-diversity are finished/confirmed)

**Comment by hputnam** [comment]
I have created the tree and edited @jrcunning code for beta. Can you check this in data_exploration @jrcunning ? I have then applied this to the PC tests and directly using several metrics.

**Comment by daniclaar** [comment]
That looks great @hputnam!
I added in constrained ordination based on our temperature metrics - 
When Porites and Acropora are analyzed separately, the temperature metrics account for ~30% and about 40% of Symbiodinium community variability, respectively (!)
Have a look at the data_exploration markdown, and let me know what you think.

**Comment by jrcunning** [comment]
@hputnam the code looks good. I modified the code slightly and added code to perform linear regressions between the distance to centroid metrics and the temperature metrics. See fb4e445. Many of these relationships are significant....

@daniclaar Can you explain the constrained ordination? I am having trouble with how to interpret these results. I ran some more constrained ordinations at the end of the data_analysis.Rmd and got some curious results....again see fb4e445....

**Comment by hputnam** [comment]
@jrcunning as per our quick chat I drafted an AICc model selection section https://github.com/hputnam/Moorea_Sym/commit/b13b46a8849f34c4e73af03ba26dd553d2780ce1. I think what this is saying is that all models are equally likely. This seems to suggest just going with PCs 1-4, or 1-2 at least... thoughts?

**Comment by daniclaar** [comment]
Hey all! Sorry for the long silence - I just got back home yesterday, and am working on catching up.  
@jrcunning - I've added in more explanation of the constrained ordination process (in the data_analysis.Rmd), please have a look and see if it makes sense.  
I have also expanded the constrained ordination analysis to dig in to it a bit more. After reading through the [ordistep (vegan) documentation](https://www.rdocumentation.org/packages/vegan/versions/2.4-2/topics/ordistep), I am not sure we can use standard AICc model selection, but with ordistep, it is possible to use "AIC-like statistics" to conduct model choice. I've included this in 3929160b1161baf0f992310f96d5a0b0b3f1682d as well. This includes model selection for both models built only with the first four PCs, and for models built only with the original temperature metrics (for Porites and Acropora separately). There is collinearity within models built using the original temperature metrics (which makes sense, because the main point of conducting the PCs is to reduce dimensionality and collinearity among our temperature variables). 
Have a look, and let me know what you think, and if all of that makes sense. We can also chat through it next time we Skype. :-)
