### ISSUE TITLE
add R tasks and validate Makefile

### ISSUE THREAD

**Issue by jrcunning** [hputnam/Moorea_Sym#24]

**Comment by jrcunning** [comment]
move code from build.phy.tree.txt into Makefile. ignore bottom chunk of code.

**Comment by jrcunning** [comment]
add temperature R script into Makefile.

**Comment by jrcunning** [comment]
Added remaining components to Makefile in 809ce55, but still need to rerun entire pipeline from scratch to validate...

**Comment by hputnam** [comment]
@jrcunning can you rerun? Do we need to update the Sym accession numbers for the ref database?

**Comment by jrcunning** [comment]
I will try to rerun on our cluster at UM this week to make sure I can get everything to work on a new machine. What do you mean about updating the accession numbers?

**Comment by hputnam** [comment]
From fetch_seqs.sh is the reference database built on an existing list of accession numbers that needs to be curated?

**Comment by hputnam** [comment]
References are up to date wrt this project
