### ISSUE TITLE
finalize figures

### ISSUE THREAD

**Issue by jrcunning** [hputnam/Moorea_Sym#25]

**Comment by jrcunning** [comment]
![img_6586 jpg](https://user-images.githubusercontent.com/8564127/27703306-e89c886e-5cd4-11e7-87ba-4f18cc2ebc5b.jpg)

**Comment by jrcunning** [comment]
make horizontal clade barplot figure 2

**Comment by jrcunning** [comment]
find new colors for clades

**Comment by jrcunning** [comment]
Created Figs 1 through 4 with d8c9da0

**Comment by hputnam** [comment]
replot 
Figure 1 with A,B,C visible
Figure 1A with map
Figure 1B with larger x and y lims
Figure 1B and 1C with clearer biplot ids
Figure 2 with dark brown for clade A? (gray too similar to light purple?)
Figure 3 with error bars in front of symbols
Figure 4 add temp metrics on  X axis

**Comment by daniclaar** [comment]
Fig 3 Panel C, move purple sites on top of green sites? (to show no difference in location but that there is a difference in dispersion)

**Comment by daniclaar** [comment]
Worked on figure 1, but I am having issues with adding the moorea map to the current plot at a high enough resolution. I tried several different approaches, and none are working right now. Will try again later.

I put the error bar symbols in front for Figure 3, and did a bit of formatting. 
After messing around with it, I think that it is actually better that the purple sites are under the green sites on this figure, so I did not change the order.

I also changed all image output from the data_analysis.Rmd to TIFF, for ms submission later on.

**Comment by daniclaar** [comment]
I tried again to get the Moorea map into Figure 1. I have used the exact same code that I used on all of my other figures with images (and it has worked fine there!) I am at a bit of a loss about what to do here. I don't really have any other ideas to try that I haven't tried already, except 1) Just putting them together in photoshop (but will not self-make in the Makefile), or 2) Getting a shapefile for Moorea (maybe Hollie you have one, or the LTER may have one available?) and just going ahead and remaking the whole figure again. Sorry guys!

**Comment by hputnam** [comment]
@daniclaar can you knit again and see if Fig 1 is finalized?

**Comment by daniclaar** [comment]
Just knitted and pushed - I've fixed panel 1A to have larger text, made all three panels similar size, and changed the labels from column names to full words. 
Should be complete in commit 4443cf51a17469deded0083811cdc5e7825bcf85 but have a look and let me know what you think!
