### ISSUE TITLE
Rerun Makefile from scratch

### ISSUE THREAD

**Issue by jrcunning** [hputnam/Moorea_Sym#29]
and remove unnecessary data and output files from GitHub

**Comment by hputnam** [comment]
After testing make file, release the version of SymITS2 that will be used for this project

**Comment by hputnam** [comment]
@jrcunning can you confirm if the SymITS2 will be in this repo, or if you will be releasing a version of your SymITS2 repo that can be used directly and referred to?

**Comment by jrcunning** [comment]
SymITS2 has been archived at Zenodo, can now be cited with this DOI:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1156380.svg)](https://doi.org/10.5281/zenodo.1156380)

**Comment by jrcunning** [comment]
Do we need to perform the 97% global OTUs, or the 100% OTUs? If we are not using any of this for the paper, we can delete these components, and their instructions in the Makefile, to streamline...

**Comment by jrcunning** [comment]
Reran Makefile from scratch and all the bioinformatics completed without error. However, I got an error on line 608 of the Rmd while knitting -- this is in the constrained ordination section, @daniclaar can you take a look?

**Comment by jrcunning** [comment]
Another thing we need to decide is which intermediate data files we want to include in the repo. Technically all we need is the compressed sequence data, the temperature data, sample metadata, and the script files. Everything else is generated by running the code. There are also a lot of files in the repo that are no longer needed in the analysis that could be deleted. I can have a go at this unless @hputnam wants to first...

**Comment by hputnam** [comment]
Feel free to start removing non-essential files @jrcunning. I can take a look later in the week. Thanks!

**Comment by daniclaar** [comment]
Yep! Will have a look to see what's up in the Rmd.

**Comment by daniclaar** [comment]
Was a bug in the released version of vegan. Used dev version (from GitHub) for sections with the problematic function anova.cca(). It's not the most pretty solution, but it works.
d19f12e
