### ISSUE TITLE
Use Slack?

### ISSUE THREAD

**Issue by daniclaar** [hputnam/Moorea_Sym#4]
Have either of you used Slack (slack.com) before? It's a "messenger for teams", and is kind of a mix of GitHub issues and Google Hangouts. You can set up different chat threads (called channels) to track similar conversations. We are using it right now for our Open Science Project (https://github.com/baumlab/open-science-project), and it's been really nice for communication. 
Let me know if you think it would be useful, and if so I can set it up!

**Comment by hputnam** [comment]
I like slack (have used for several projects), but feel it can be redundant with GH... if people are happy to do everything through GH issues.  I have been happy with communicating through GH issues  as it puts everything about the project in a single location (e.g., data, discussions, analysis, and output). Let me know how you guys feel about keeping everything in GH.

**Comment by daniclaar** [comment]
Sure, no problem! Just wanted to throw it out as an option :)

**Comment by hputnam** [comment]
:thumbsup:
