### ISSUE TITLE
Thoughts on 97% OTU and/vs MED?

### ISSUE THREAD

**Issue by hputnam** [hputnam/Moorea_Sym#5]
Maybe we can chat about this on Wednesday.  Does anyone have access to the full text of the Smith paper? http://www.nature.com/ismej/journal/vaop/ncurrent/full/ismej2016206a.html?WT.feed_name=subjects_microbiology

**Comment by daniclaar** [comment]
Thanks to Ross, yes I do! :-)
[The ISME Journal 2017 Smith.pdf](https://github.com/hputnam/Moorea_Sym/files/802323/The.ISME.Journal.2017.Smith.pdf)

I know we are most likely not going to use WGCNA for this project, but I am particularly interested in seeing if a MED/WGCNA combined approach could be used to look at IGV...

**Comment by hputnam** [comment]
and the important parts are already highlighted 👍 Thanks!

**Comment by hputnam** [comment]
Do you have the supp methods too?

**Comment by daniclaar** [comment]
Haha whoops, forgot I sent the highlighted one! :) 
No, but @jrcunning might?

**Comment by jrcunning** [comment]
[ismej2016206x1.docx](https://github.com/hputnam/Moorea_Sym/files/802447/ismej2016206x1.docx)
![ismej2016206x2](https://cloud.githubusercontent.com/assets/8564127/23345313/2c20128a-fc5a-11e6-9376-f99f82e8367e.jpg)
![ismej2016206x3](https://cloud.githubusercontent.com/assets/8564127/23345312/2c1fc3a2-fc5a-11e6-911b-627f23d1b566.jpg)
![ismej2016206x4](https://cloud.githubusercontent.com/assets/8564127/23345314/2c217418-fc5a-11e6-8334-0b1648377342.jpg)
![ismej2016206x5](https://cloud.githubusercontent.com/assets/8564127/23345315/2c221c42-fc5a-11e6-9db1-6785c91a1c7f.jpg)
![ismej2016206x6](https://cloud.githubusercontent.com/assets/8564127/23345316/2c2b2b48-fc5a-11e6-8f83-2522649162cc.jpg)
![ismej2016206x7](https://cloud.githubusercontent.com/assets/8564127/23345317/2c34a1dc-fc5a-11e6-8d99-b67b94b55a76.jpg)
[ismej2016206x8.xlsx](https://github.com/hputnam/Moorea_Sym/files/802449/ismej2016206x8.xlsx)
[ismej2016206x9.docx](https://github.com/hputnam/Moorea_Sym/files/802451/ismej2016206x9.docx)
[ismej2016206x10.xlsx](https://github.com/hputnam/Moorea_Sym/files/802450/ismej2016206x10.xlsx)
[ismej2016206x11.docx](https://github.com/hputnam/Moorea_Sym/files/802448/ismej2016206x11.docx)

**Comment by jrcunning** [comment]
I also got the sequence data (fasta files) from Smith in case we want to have a closer look...

**Comment by daniclaar** [comment]
We decided (during Skype meeting March 1st) to not use MED for this analysis.
