### ISSUE TITLE
Yost_1944F_fixed.fna file?

### ISSUE THREAD

**Issue by jrcunning** [hputnam/Moorea_Sym#6]
The Yost_1944F.fna file we are using now has 567462 sequences in it. However, the previous Yost_1944F_fixed.fna file that Hollie provided on Google Drive on 11/22/16 (not sure where it came from or how you generated it?) that I analyzed a while back (see the "fixed" directory in Bioinf) has 789478 sequences! How is this possible? Sample 101, for example, has 394 sequences in the Yost_1944F.fna file, but 877 sequences in the Yost_1944F_fixed.fna file. Hollie, can you remember how you generated this Yost_1944F_fixed.fna file (how did it end up with more data in it?), and if not, can you confirm that we should NOT be using it, and should instead only use the Yost_1944F.fna file in the Yost_1944Fasta09132012.zip archive?  Depending on which fna file is used, the results are different. For example 101 contains significant amount of clade D in the Yost_1944F_fixed.fna file, but not in the Yost_1944F.fna file.

**Comment by jrcunning** [comment]
samples    101      112       182      were rerun on a subsequent 454 run... I will add these sequences to the original Yost_1944 library and this will be our final sequence file that we will use...

**Comment by hputnam** [comment]
Yost run names that contain Moorea samples
Yost_1944Fasta09132012 = initial run
Yost_2172Fasta12052012 = re-runs for low reads in original samples

**Comment by jrcunning** [comment]
Also for the record: we decided that the Yost_1944F_fixed.fna file is not reproducible at this point, and therefore should not be used, even for benchmarking/comparison.
